name: scanner
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0

environment:
  sdk: ^3.5.4

dependencies:
  animated_custom_dropdown: ^3.1.1
  animated_text_kit: ^4.2.2
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.8
  data_table_2: ^2.5.15
  file_selector: ^1.0.3
  filesize: 
    git:
      url: https://github.com/guchengxi1994/filesize_plus.git
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_rust_bridge: 2.5.1
  flutter_tags_x: ^1.1.0
  freezed_annotation: ^2.4.4
  loading_indicator: ^3.1.1
  logging: ^1.2.0
  riverpod: ^2.5.1
  rust_lib_scanner:
    path: rust_builder
  square_progress_bar: ^1.1.1
  toastification: ^2.1.0
  treemap:
    git:
      url: https://github.com/guchengxi1994/treemap.git
      ref: cb2ba3aa0a35e151d4ea03771966c3fad72d7786
  window_manager: ^0.4.0

dev_dependencies:
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^5.0.0
  freezed: ^2.5.7


# dependency_overrides:
#   treemap:
#     path: D:/github_repo/treemap
#   filesize:
#     path: D:/github_repo/filesize_plus

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon.jpeg
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package


flutter_launcher_icons:   # flutter pub run flutter_launcher_icons
  image_path: "assets/icon.jpeg"
  web:
    generate: true
    image_path: "assets/icon.jpeg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon.jpeg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon.jpeg"

## rename setAppName --targets linux,windows,macos --value "scanner" 
