// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ProjectDetail {
  final String path;
  final BigInt size;
  final BigInt count;

  const ProjectDetail({
    required this.path,
    required this.size,
    required this.count,
  });

  @override
  int get hashCode => path.hashCode ^ size.hashCode ^ count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectDetail &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          size == other.size &&
          count == other.count;
}
