// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

class OperationResult {
  final bool success;
  final String message;

  const OperationResult({
    required this.success,
    required this.message,
  });

  static Future<OperationResult> fileRemoveFailed() =>
      RustLib.instance.api.crateApiPublicOperationResultFileRemoveFailed();

  static Future<OperationResult> fileRemoveOk() =>
      RustLib.instance.api.crateApiPublicOperationResultFileRemoveOk();

  @override
  int get hashCode => success.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OperationResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          message == other.message;
}
