// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.2.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class File {
  final String path;
  final String name;
  final BigInt size;

  const File({
    required this.path,
    required this.name,
    required this.size,
  });

  @override
  int get hashCode => path.hashCode ^ name.hashCode ^ size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is File &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          name == other.name &&
          size == other.size;
}
